// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_1Cmo7qII_6onybyb9Fy0rZ2X0pXTds',
    appId: '1:133939376227:web:aa26721cd290211e528856',
    messagingSenderId: '133939376227',
    projectId: 'budget-wise-81413',
    authDomain: 'budget-wise-81413.firebaseapp.com',
    storageBucket: 'budget-wise-81413.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQyELjq2DNzwdIb36caKXVN9WVuA6Lhp8',
    appId: '1:133939376227:android:ef92c61232062074528856',
    messagingSenderId: '133939376227',
    projectId: 'budget-wise-81413',
    storageBucket: 'budget-wise-81413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtdequlNWAUWpKyctq7C7K7HUZY-IOUU0',
    appId: '1:133939376227:ios:bba0dbc1c32ad92a528856',
    messagingSenderId: '133939376227',
    projectId: 'budget-wise-81413',
    storageBucket: 'budget-wise-81413.firebasestorage.app',
    androidClientId: '133939376227-sjls6gefd47cdrfrlo9rne82b6luv0od.apps.googleusercontent.com',
    iosClientId: '133939376227-s0t61t1cfufuk460pj6ek10po271mrhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtdequlNWAUWpKyctq7C7K7HUZY-IOUU0',
    appId: '1:133939376227:ios:bba0dbc1c32ad92a528856',
    messagingSenderId: '133939376227',
    projectId: 'budget-wise-81413',
    storageBucket: 'budget-wise-81413.firebasestorage.app',
    androidClientId: '133939376227-sjls6gefd47cdrfrlo9rne82b6luv0od.apps.googleusercontent.com',
    iosClientId: '133939376227-s0t61t1cfufuk460pj6ek10po271mrhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk_1Cmo7qII_6onybyb9Fy0rZ2X0pXTds',
    appId: '1:133939376227:web:566ce404277d6fd6528856',
    messagingSenderId: '133939376227',
    projectId: 'budget-wise-81413',
    authDomain: 'budget-wise-81413.firebaseapp.com',
    storageBucket: 'budget-wise-81413.firebasestorage.app',
  );

}