// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAknJmI-UrfjplxOaj5AATKbAzdwoEUS40',
    appId: '1:997110563290:web:1c50d63f0be96c26ce00e3',
    messagingSenderId: '997110563290',
    projectId: 'budgetwise-38a4b',
    authDomain: 'budgetwise-38a4b.firebaseapp.com',
    storageBucket: 'budgetwise-38a4b.firebasestorage.app',
    measurementId: 'G-JL9BCYHZ66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp7tW0elFbU0Bl1zNYDxt1BdToQwJLFkg',
    appId: '1:997110563290:android:98b95b7fa3486aa2ce00e3',
    messagingSenderId: '997110563290',
    projectId: 'budgetwise-38a4b',
    storageBucket: 'budgetwise-38a4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCZR59FS9md19Dut2jxb1JmJ6atWoZPWI',
    appId: '1:997110563290:ios:5653e3c494cf5fc1ce00e3',
    messagingSenderId: '997110563290',
    projectId: 'budgetwise-38a4b',
    storageBucket: 'budgetwise-38a4b.firebasestorage.app',
    iosBundleId: 'com.example.budgetWise',
  );
}
