name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3' 

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze
      continue-on-error: true

    - name: Run tests
      run: flutter test

    - name: Build APK (debug)
      run: flutter build apk --debug
